import "./globals.css";
import { Inter } from "next/font/google";
import Nav from "@/components/Nav";
import { Montserrat } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });
const monts = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${monts.className}  mx-20 mt-1 my-12`}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
